# Generated by Django 3.2.6 on 2024-12-06 15:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unique_identifier', models.CharField(blank=True, max_length=50, unique=True)),
                ('system_name', models.CharField(choices=[('BSS_ESF', 'BSS ESF'), ('IRM', 'IRM'), ('CIS', 'CIS'), ('ECW_SP', 'ECW SP')], max_length=50)),
                ('domain', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('error_count', models.IntegerField()),
                ('error_reason', models.TextField()),
                ('source_type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('validation_status', models.CharField(choices=[('Pending', 'Pending'), ('Validated', 'Validated'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('processed_flag', models.BooleanField(default=False)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('inserted_by', models.CharField(default='Automated_Script', max_length=50)),
            ],
        ),
    ]
