# Generated by Django 3.2.6 on 2025-01-27 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources_data_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FicheErreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=50)),
                ('service_type', models.CharField(max_length=100)),
                ('service_name', models.CharField(max_length=100)),
                ('error_count', models.IntegerField()),
                ('error_reason', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('priorite', models.CharField(default='Normale', max_length=50)),
                ('statut', models.CharField(default='Ouvert', max_length=50)),
                ('symptomes_observes', models.TextField(blank=True)),
                ('logs_messages', models.TextField(blank=True)),
                ('gravite', models.CharField(default='Moyenne', max_length=50)),
                ('services_affectes', models.TextField(blank=True)),
                ('cause', models.TextField(blank=True)),
                ('hypotheses', models.TextField(blank=True)),
                ('prochaines_actions', models.TextField(blank=True)),
                ('responsable_resolution', models.CharField(blank=True, max_length=100)),
                ('commentaires', models.TextField(blank=True)),
                ('type_erreur', models.CharField(blank=True, max_length=100)),
                ('impact_utilisateur', models.CharField(blank=True, max_length=100)),
                ('statut_resolution', models.CharField(default='Non commencé', max_length=50)),
                ('historique_actions', models.TextField(blank=True)),
                ('equipe_responsable', models.CharField(blank=True, max_length=100)),
                ('priorite_numerique', models.IntegerField(default=5)),
                ('frequence', models.CharField(blank=True, max_length=50)),
                ('automatisation_possible', models.BooleanField(default=False)),
                ('version_systeme', models.CharField(blank=True, max_length=50)),
                ('comportement_attendu', models.TextField(blank=True)),
                ('comportement_observe', models.TextField(blank=True)),
                ('delai_resolution', models.DurationField(blank=True, null=True)),
                ('delai_ecoule', models.DurationField(blank=True, null=True)),
                ('impact_financier', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nombre_utilisateurs_impactes', models.IntegerField(blank=True, null=True)),
                ('zone_geographique_affectee', models.CharField(blank=True, max_length=100)),
                ('categorie_erreur', models.CharField(blank=True, max_length=50)),
                ('niveau_criticite', models.IntegerField(default=3)),
                ('etape_detection', models.CharField(blank=True, max_length=100)),
                ('notifications_envoyees', models.BooleanField(default=False)),
                ('canaux_communication', models.CharField(blank=True, max_length=100)),
                ('parties_prenantes', models.TextField(blank=True)),
                ('solution_proposee', models.TextField(blank=True)),
                ('solution_implantee', models.TextField(blank=True)),
                ('efficacite_solution', models.IntegerField(blank=True, null=True)),
                ('tests_effectues', models.TextField(blank=True)),
                ('timestamp_modification', models.DateTimeField(auto_now=True)),
                ('precedent_incidents_similaires', models.TextField(blank=True)),
                ('resolution_automatique_possible', models.BooleanField(default=False)),
                ('audit_log', models.TextField(blank=True)),
                ('documentation_associee', models.TextField(blank=True)),
                ('code_erreur', models.CharField(blank=True, max_length=50)),
                ('fichiers_impactes', models.TextField(blank=True)),
                ('charge_systeme', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('analysts', models.TextField(blank=True)),
                ('erreur_normale', models.BooleanField(default=False)),
                ('source_data', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sources_data_app.sourcedata')),
            ],
        ),
    ]
