# Generated by Django 3.2.6 on 2025-03-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_auto_20250130_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheerreur',
            name='timestamp',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AddConstraint(
            model_name='ficheerreur',
            constraint=models.UniqueConstraint(fields=('system_name', 'error_reason'), name='unique_system_error'),
        ),
    ]
