# Generated by Django 3.2.6 on 2025-03-20 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management_systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorevent',
            name='logs',
            field=models.TextField(blank=True, verbose_name='Messages de logs'),
        ),
    ]
