# Generated by Django 3.2.6 on 2025-03-19 09:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('error_management_systems', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='errorevent',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Error Event', 'verbose_name_plural': 'Error Events'},
        ),
        migrations.AlterModelOptions(
            name='errorticket',
            options={'verbose_name': 'Error Ticket', 'verbose_name_plural': 'Error Tickets'},
        ),
        migrations.AlterModelOptions(
            name='errortype',
            options={'verbose_name': 'Error Type', 'verbose_name_plural': 'Error Types'},
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='error_count',
            field=models.IntegerField(verbose_name='Error Count'),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='error_reason',
            field=models.TextField(verbose_name='Error Reason'),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='error_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='error_management_systems.errortype', verbose_name='Error Type'),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='inserted_by',
            field=models.CharField(max_length=50, verbose_name='Inserted by'),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='service_type',
            field=models.CharField(max_length=100, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='system_name',
            field=models.CharField(max_length=50, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='errorevent',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='actions',
            field=models.TextField(blank=True, verbose_name='Planned Actions'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='cause_racine',
            field=models.TextField(blank=True, verbose_name='Root Cause'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='charge_systeme',
            field=models.IntegerField(blank=True, null=True, verbose_name='System Load'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='commentaires',
            field=models.TextField(blank=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='date_modification',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='date_resolution',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Resolution Date'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='equipe',
            field=models.CharField(blank=True, max_length=100, verbose_name='Assigned Team'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='error_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='error_management_systems.errortype', verbose_name='Error Type'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='historique',
            field=models.JSONField(blank=True, default=dict, verbose_name='Modification History'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='hypotheses',
            field=models.TextField(blank=True, verbose_name='Hypotheses'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='impact',
            field=models.TextField(blank=True, verbose_name='User Impact'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='niveau_criticite',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Criticality Level (1-5)'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='nombre_utilisateurs',
            field=models.IntegerField(blank=True, null=True, verbose_name='Impacted Users'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='priorite',
            field=models.CharField(choices=[('P1', 'Critical'), ('P2', 'High'), ('P3', 'Normal'), ('P4', 'Low')], default='P3', max_length=2, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsible'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='services_affectes',
            field=models.TextField(blank=True, verbose_name='Affected Services'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Implemented Solution'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='statut',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], default='OPEN', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='symptomes',
            field=models.TextField(blank=True, verbose_name='Observed Symptoms'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='code_erreur',
            field=models.CharField(blank=True, max_length=50, verbose_name='Error Code'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='comportement_attendu',
            field=models.TextField(blank=True, verbose_name='Expected Behavior'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='description_technique',
            field=models.TextField(blank=True, verbose_name='Detailed Technical Description'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='environnement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Environment (OS, version, etc.)'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='error_reason',
            field=models.TextField(verbose_name='Error Reason'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='fichiers_impactes',
            field=models.TextField(blank=True, verbose_name='Impacted Files/Modules'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='logs',
            field=models.TextField(blank=True, verbose_name='Log Messages'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='niveau_severite',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Severity Level (1-5)'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='procedures_contournement',
            field=models.TextField(blank=True, verbose_name='Workaround Procedures'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='service_name',
            field=models.CharField(max_length=100, verbose_name='Service Name'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='service_type',
            field=models.CharField(max_length=100, verbose_name='Service Type'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='system_name',
            field=models.CharField(max_length=50, verbose_name='System Name'),
        ),
        migrations.AlterField(
            model_name='errortype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
    ]
