# Generated by Django 3.2.6 on 2025-03-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management_systems', '0002_auto_20250319_0927'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='errortype',
            name='1unique_system_error_reason',
        ),
        migrations.RemoveField(
            model_name='errortype',
            name='comportement_attendu',
        ),
        migrations.RemoveField(
            model_name='errortype',
            name='description_technique',
        ),
        migrations.RemoveField(
            model_name='errortype',
            name='environnement',
        ),
        migrations.RemoveField(
            model_name='errortype',
            name='logs',
        ),
        migrations.RemoveField(
            model_name='errortype',
            name='niveau_severite',
        ),
        migrations.RemoveField(
            model_name='errortype',
            name='procedures_contournement',
        ),
        migrations.AddField(
            model_name='errorticket',
            name='documented_knowledge_base',
            field=models.BooleanField(default=False, verbose_name='Documented in Knowledge Base'),
        ),
        migrations.AddField(
            model_name='errorticket',
            name='lessons_learned',
            field=models.TextField(blank=True, verbose_name='Lessons Learned'),
        ),
        migrations.AddField(
            model_name='errorticket',
            name='validation_responsable',
            field=models.BooleanField(default=False, verbose_name='Validated by Responsible'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='error_category',
            field=models.CharField(choices=[('logic', 'Logic'), ('performance', 'Performance'), ('security', 'Security'), ('integration', 'Integration'), ('data', 'Data'), ('configuration', 'Configuration')], default='logic', max_length=50, verbose_name='Error Category'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='error_type',
            field=models.CharField(choices=[('expected', 'Expected'), ('unexpected', 'Unexpected')], default='unexpected', max_length=50, verbose_name='Error Type'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='impact_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20, verbose_name='Impact Level'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='occurred_at',
            field=models.DateTimeField(default='Unknown', verbose_name='Occurrence Timestamp'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='request_payload',
            field=models.JSONField(blank=True, null=True, verbose_name='Request Payload'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='source_component',
            field=models.CharField(blank=True, max_length=100, verbose_name='Source Component'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='stack_trace',
            field=models.TextField(blank=True, verbose_name='Stack Trace'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='trigger_event',
            field=models.TextField(blank=True, verbose_name='Trigger Event'),
        ),
        migrations.AddConstraint(
            model_name='errortype',
            constraint=models.UniqueConstraint(fields=('system_name', 'service_name', 'error_reason'), name='unique_system_error_reason'),
        ),
    ]
