# Generated by Django 4.2.20 on 2025-03-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management_systems', '0002_errorevent_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='errortype',
            name='service_classification',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Service'), ('secondary', 'Secondary Service'), ('tertiary', 'Tertiary Service'), ('external', 'External Service')], max_length=50, null=True, verbose_name='Service Classification'),
        ),
        migrations.AddField(
            model_name='errortype',
            name='system_classification',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1, null=True, verbose_name='System Classification'),
        ),
    ]
