# Generated by Django 4.2.20 on 2025-03-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management_systems', '0003_errortype_service_classification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorticket',
            name='statut',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=15, verbose_name='Status'),
        ),
    ]
