# Generated by Django 3.2.6 on 2025-03-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management_systems', '0003_auto_20250320_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errortype',
            name='occurred_at',
            field=models.DateTimeField(blank=True, verbose_name='Occurrence Timestamp'),
        ),
    ]
