# Generated by Django 4.2.20 on 2025-03-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management_systems', '0004_alter_errorticket_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorticket',
            name='niveau_criticite',
        ),
        migrations.AlterField(
            model_name='errorticket',
            name='priorite',
            field=models.CharField(editable=False, max_length=20, verbose_name='Priority'),
        ),
    ]
