# Generated by Django 4.2.20 on 2025-03-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_management_systems', '0005_remove_errorticket_niveau_criticite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorticket',
            name='priorite',
            field=models.CharField(choices=[('P1', 'Critical'), ('P2', 'High'), ('P3', 'Normal'), ('P4', 'Low')], default='P3', max_length=2, verbose_name='Priority'),
        ),
    ]
