# Generated by Django 3.2.6 on 2025-03-07 10:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference_id', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Identifiant unique')),
                ('error_count', models.IntegerField(verbose_name="Nombre d'erreurs")),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horodatage')),
                ('domain', models.CharField(max_length=100, verbose_name='Domaine')),
                ('logs', models.TextField(blank=True, verbose_name='Messages de logs')),
                ('version_system', models.CharField(blank=True, max_length=50, verbose_name='Version du système')),
                ('inserted_by', models.CharField(max_length=50, verbose_name='Enregistré par')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': "Événement d'erreur",
                'verbose_name_plural': "Événements d'erreurs",
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ErrorTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('priorite', models.CharField(choices=[('P1', 'Critique'), ('P2', 'Haute'), ('P3', 'Normale'), ('P4', 'Basse')], default='P3', max_length=2, verbose_name='Priorité')),
                ('statut', models.CharField(choices=[('OPEN', 'Ouvert'), ('IN_PROGRESS', 'En cours'), ('PENDING', 'En attente'), ('RESOLVED', 'Résolu'), ('CLOSED', 'Fermé')], default='OPEN', max_length=15, verbose_name='Statut')),
                ('niveau_criticite', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Criticité (1-5)')),
                ('symptomes', models.TextField(blank=True, verbose_name='Symptômes observés')),
                ('impact', models.TextField(blank=True, verbose_name='Impact utilisateur')),
                ('services_affectes', models.TextField(blank=True, verbose_name='Services affectés')),
                ('nombre_utilisateurs', models.IntegerField(blank=True, null=True, verbose_name='Utilisateurs impactés')),
                ('cause_racine', models.TextField(blank=True, verbose_name='Cause racine')),
                ('hypotheses', models.TextField(blank=True, verbose_name='Hypothèses')),
                ('responsable', models.CharField(blank=True, max_length=100, verbose_name='Responsable')),
                ('equipe', models.CharField(blank=True, max_length=100, verbose_name='Équipe assignée')),
                ('actions', models.TextField(blank=True, verbose_name='Actions prévues')),
                ('solution', models.TextField(blank=True, verbose_name='Solution implémentée')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('date_resolution', models.DateTimeField(blank=True, null=True, verbose_name='Date de résolution')),
                ('commentaires', models.TextField(blank=True, verbose_name='Commentaires')),
                ('historique', models.JSONField(blank=True, default=dict, verbose_name='Historique des modifications')),
            ],
            options={
                'verbose_name': "Ticket d'erreur",
                'verbose_name_plural': "Tickets d'erreurs",
            },
        ),
        migrations.CreateModel(
            name='ErrorType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system_name', models.CharField(max_length=50, verbose_name='Nom du système')),
                ('service_type', models.CharField(max_length=100, verbose_name='Type de service')),
                ('service_name', models.CharField(max_length=100, verbose_name='Nom du service')),
                ('error_reason', models.TextField(verbose_name="Raison de l'erreur")),
                ('code_erreur', models.CharField(blank=True, max_length=50, verbose_name="Code d'erreur")),
                ('comportement_attendu', models.TextField(blank=True, verbose_name='Comportement attendu')),
                ('correction_automatique', models.BooleanField(default=False, verbose_name='Correction automatique possible')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
            ],
            options={
                'verbose_name': "Type d'erreur",
                'verbose_name_plural': "Types d'erreurs",
            },
        ),
        migrations.AddConstraint(
            model_name='errortype',
            constraint=models.UniqueConstraint(fields=('system_name', 'error_reason'), name='unique_system_error_reason'),
        ),
        migrations.AddField(
            model_name='errorticket',
            name='error_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='ems_app.errortype', verbose_name="Type d'erreur"),
        ),
        migrations.AddField(
            model_name='errorevent',
            name='error_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='ems_app.errortype', verbose_name="Type d'erreur"),
        ),
    ]
